
-- 1. Cria a Tabela "Departamentos"
CREATE TABLE IF NOT EXISTS departamentos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome text NOT NULL UNIQUE,
    created_at timestamptz DEFAULT now()
);

-- 2. Insere os Departamentos Iniciais (Ex: Social)
INSERT INTO departamentos (nome)
VALUES ('Social')
ON CONFLICT (nome) DO NOTHING;

-- 3. Alterar Usuários para ter Departamento (FK)
-- Adiciona a coluna departamento_id na tabela usuarios
ALTER TABLE usuarios 
ADD COLUMN IF NOT EXISTS departamento_id bigint REFERENCES departamentos(id);

-- 4. Alterar Solicitações para ter Departamento (FK)
-- Adiciona a coluna departamento_id na tabela solicitacoes (para relatórios ocultos)
ALTER TABLE solicitacoes 
ADD COLUMN IF NOT EXISTS departamento_id bigint REFERENCES departamentos(id);

-- 5. Criar Usuários de Exemplo (Social 1, 2, 3)
-- Precisa pegar o ID do Social primeiro
DO $$
DECLARE
    social_id bigint;
BEGIN
    SELECT id INTO social_id FROM departamentos WHERE nome = 'Social';
    
    -- Inserir usuário Social 1
    INSERT INTO usuarios (email, senha, nome, perfil, departamento, departamento_id)
    VALUES ('social1@hebraica.org.br', '123456', 'Social 1', 'solicitante', 'Social', social_id)
    ON CONFLICT (email) DO NOTHING;

    -- Inserir usuário Social 2
    INSERT INTO usuarios (email, senha, nome, perfil, departamento, departamento_id)
    VALUES ('social2@hebraica.org.br', '123456', 'Social 2', 'solicitante', 'Social', social_id)
    ON CONFLICT (email) DO NOTHING;

    -- Inserir usuário Social 3
    INSERT INTO usuarios (email, senha, nome, perfil, departamento, departamento_id)
    VALUES ('social3@hebraica.org.br', '123456', 'Social 3', 'solicitante', 'Social', social_id)
    ON CONFLICT (email) DO NOTHING;
END $$;
